/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

//
#import "BackRow-Structs.h"

@class NSMutableArray, NSThread;
@protocol VSSpeechHiddenProtocol;

__attribute__((visibility("hidden")))
@interface BRVoiceOverSpeechManager : NSObject {
@private
	NSMutableArray *_speechQueue;	// 4 = 0x4
	NSObject<VSSpeechHiddenProtocol> *_synthesizer;	// 8 = 0x8
	NSThread *_runThread;	// 12 = 0xc
	BOOL _runLoopEnabled;	// 16 = 0x10
	BOOL _didInitialize;	// 17 = 0x11
	BOOL _isSpeaking;	// 18 = 0x12
}
@property(readonly, assign) BOOL isSpeaking;	// G=0x32e583f9; converted property
@property(assign, nonatomic) float speechRate;	// G=0x32e583b9; S=0x32e5931d; @dynamic
+ (URegularExpression *)createRegularExpressionFromString:(id)string;	// 0x32e593e1
+ (id)matchedRangesForString:(id)string withRegularExpression:(URegularExpression *)regularExpression;	// 0x32e59459
- (id)init;	// 0x32e58d89
- (void)_clearSpeechQueue;	// 0x32e5867d
- (void)_continueSpeaking;	// 0x32e58551
- (void)_dispatchSpeechAction:(id)action;	// 0x32e5869d
- (void)_initialize;	// 0x32e58f99
- (void)_isSpeaking:(id)speaking;	// 0x32e58461
- (void)_pauseSpeaking;	// 0x32e585ad
- (id)_preprocessString:(id)string;	// 0x32e587c1
- (id)_processDurationStrings:(id)strings;	// 0x32e590ed
- (void)_setSpeechRate:(id)rate;	// 0x32e58359
- (void)_speechJobFinished:(BOOL)finished;	// 0x32e58b49
- (void)_startNextSpeechJob;	// 0x32e58949
- (void)_stopSpeaking;	// 0x32e584f1
- (void)clearSpeechQueue;	// 0x32e58641
- (void)continueSpeaking;	// 0x32e58515
- (void)dealloc;	// 0x32e58cdd
- (void)dispatchSpeechAction:(id)action;	// 0x32e585d1
// converted property getter: - (BOOL)isSpeaking;	// 0x32e583f9
- (void)pauseSpeaking;	// 0x32e58571
- (void)setMaintainConnection:(BOOL)connection;	// 0x32e58c05
// declared property setter: - (void)setSpeechRate:(float)rate;	// 0x32e5931d
// declared property getter: - (float)speechRate;	// 0x32e583b9
- (void)speechSynthesizer:(id)synthesizer didFinishSpeaking:(BOOL)speaking withError:(id)error;	// 0x32e593b5
- (void)stopSpeaking;	// 0x32e584b5
@end

