/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRSingleton.h"

@class NSArray, NSMutableArray, NSString, NSTimer, BRVoiceOverSpeechManager, NSDictionary;

@interface BRVoiceOver : BRSingleton {
@private
	NSTimer *_focusChangeTimer;	// 4 = 0x4
	NSTimer *_screenContentTimer;	// 8 = 0x8
	NSDictionary *_languageToLocale;	// 12 = 0xc
	NSMutableArray *_focusChain;	// 16 = 0x10
	BRVoiceOverSpeechManager *_speechManager;	// 20 = 0x14
	BOOL _isEnabled;	// 24 = 0x18
	BOOL *_handleFocusChangeCancel;	// 28 = 0x1c
	int _speechRate;	// 32 = 0x20
	BOOL _inRereadMode;	// 36 = 0x24
	id _focusChangeObserver;	// 40 = 0x28
	id _noFocusChangeObserver;	// 44 = 0x2c
	NSDictionary *_phoneticsTable;	// 48 = 0x30
	int _lastEvent;	// 52 = 0x34
	id _lastFocusedElement;	// 56 = 0x38
	NSString *_previousContainerString;	// 60 = 0x3c
	NSMutableArray *_previousContainerStrings;	// 64 = 0x40
	NSString *_previousSecondaryScreenInfo;	// 68 = 0x44
	NSString *_previousContextChangeString;	// 72 = 0x48
	NSArray *_previousElementTraits;	// 76 = 0x4c
	NSString *_previousTextFieldValue;	// 80 = 0x50
	NSString *_initialText;	// 84 = 0x54
	id _initialTextControl;	// 88 = 0x58
}
@property(assign, nonatomic) BOOL isEnabled;	// G=0x32e55429; S=0x32e560f1; @synthesize=_isEnabled
@property(assign, nonatomic) int speechRate;	// G=0x32e563a1; S=0x32e5631d; @synthesize=_speechRate
+ (BOOL)isEnabled;	// 0x32e55401
+ (void)setSingleton:(id)singleton;	// 0x32e5541d
+ (id)singleton;	// 0x32e55411
- (id)init;	// 0x32e56d3d
- (void)_chapterMarkersHidden:(id)hidden;	// 0x32e564e9
- (void)_chapterMarkersShown:(id)shown;	// 0x32e56525
- (void)_clearCachedElementInformation;	// 0x32e55cb5
- (void)_coalesceHandleFocusChange:(id)change;	// 0x32e55779
- (void)_contextDidChange:(id)_context;	// 0x32e55695
- (id)_determineAccessibilityLanguage:(id)language;	// 0x32e55a6d
- (id)_determineControlTraits:(id)traits;	// 0x32e57075
- (id)_determineKeyboardType:(id)type;	// 0x32e55ad5
- (id)_determineScreenChangeLabel:(id)label;	// 0x32e5728d
- (id)_determineScreenSecondaryInfo:(id)info;	// 0x32e55e45
- (id)_determineTextFieldData:(id)data;	// 0x32e55e9d
- (id)_focusChain:(id)chain;	// 0x32e55439
- (void)_handleFocusChange:(id)change;	// 0x32e576a9
- (id)_handleFocusChangeSpecialCases:(id)cases;	// 0x32e5701d
- (void)_handleFocusDidNotChange:(id)_handleFocus;	// 0x32e55a0d
- (void)_handleRereadMode;	// 0x32e55629
- (void)_handleScreenContentOutput:(id)output;	// 0x32e55d65
- (void)_initialize;	// 0x32e569cd
- (void)_languageChanged:(id)changed;	// 0x32e56619
- (id)_makeFocusChain:(id)chain;	// 0x32e56095
- (void)_mediaContentSkipped:(id)skipped;	// 0x32e56561
- (void)_mediaPlaybackStarted:(id)started;	// 0x32e55c85
- (void)_outputControl:(id)control;	// 0x32e57895
- (id)_phoneticLetterForControl:(id)control;	// 0x32e55b81
- (id)_replacePasswordBullets:(id)bullets;	// 0x32e56f15
- (void)_startSpeechManager;	// 0x32e568f5
- (void)_tearDown;	// 0x32e566d9
- (void)_updateFocusChain:(id)chain;	// 0x32e55c2d
- (void)_updateFocusedElement:(id)element;	// 0x32e55a2d
- (void)_updateSpeechRate;	// 0x32e563e1
- (void)dealloc;	// 0x32e56659
- (void)dispatchSpeechJob:(id)job shouldQueue:(BOOL)queue;	// 0x32e57749
- (BOOL)handleEventAction:(id)action;	// 0x32e5640d
// declared property getter: - (BOOL)isEnabled;	// 0x32e55429
- (void)setInitialText:(id)text forControl:(id)control;	// 0x32e55549
// declared property setter: - (void)setIsEnabled:(BOOL)enabled;	// 0x32e560f1
// declared property setter: - (void)setSpeechRate:(int)rate;	// 0x32e5631d
- (void)speakGreetingMessage;	// 0x32e5629d
- (void)speakString:(id)string;	// 0x32e554ed
// declared property getter: - (int)speechRate;	// 0x32e563a1
- (void)textChanged:(id)changed;	// 0x32e57ed1
- (void)updateStatus;	// 0x32e56941
@end

